apiVersion: v1
kind: Service
metadata:
  name:  ml-server-prod
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /ml-server-prod/health
spec:
  selector:
    app:  ml-server-prod
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
  type: NodePort